title: Bookish Octo Dollop
description: A starter site based on JTD
theme: just-the-docs

url: https://dougaitken.github.io/bookish-octo-dollop/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
